### PR TITLE
Feature/fix ansible 21

### PR DESCRIPTION
**Pull request by flibbertigibbet**
This will break compatibility with pre-2.0 ansibles, but fixes usage on 2.1+, which disallows `sudo`.

Also fixes NFS locking issues on Linux.

(Not intending to merge this in, due to incompatibility with older ansibles.)

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Looks like pipelining may have silently skipped some steps, so this probably isn't good to go yet.

**Comment by flibbertigibbet** [comment]
This should be ready to go in now, for a minimum ansible version of 1.9.

**Comment by flibbertigibbet** [comment]
Ansible `bundler` usage will require a minimum ansible of 2.0; `become_user` requires minimum of 1.9.

**Comment by CloudNiner** [comment]
K thanks. Provisioning to test now.

**Comment by CloudNiner** [comment]
Provision on ansible 2.0 worked great, testing 2.1 now.

**Comment by CloudNiner** [comment]
+1

**Pull request merged**
